// Temporary fake data so /listings/[id]/edit and local dev work before
// Taoufik's real API/database is ready. Placeholder — will be replaced
// when the skeleton is merged.

import type { Listing } from "./types";

export const mockListings: Listing[] = [
  {
    id: "1",
    ownerId: "u1",
    ownerName: "Alice Rossi",
    ownerEmail: "alice.rossi@school.edu",
    city: "Milan",
    neighbourhood: "Navigli",
    rent: 750,
    currency: "EUR",
    availableFrom: "2026-01-15",
    availableUntil: "2026-06-30",
    rooms: 1,
    description:
      "Cozy studio near the Navigli canals, 5 minutes from the metro. Fully furnished, great for a student on exchange.",
    photos: [],
    status: "active",
    createdAt: "2025-11-01T10:00:00.000Z",
  },
  {
    id: "2",
    ownerId: "u2",
    ownerName: "Marco Bianchi",
    ownerEmail: "marco.bianchi@school.edu",
    city: "Milan",
    neighbourhood: "Isola",
    rent: 900,
    currency: "EUR",
    availableFrom: "2026-02-01",
    availableUntil: null,
    rooms: 2,
    description:
      "Bright two-room apartment in the trendy Isola district, close to Porta Garibaldi station and lots of cafes.",
    photos: [],
    status: "active",
    createdAt: "2025-11-03T10:00:00.000Z",
  },
  {
    id: "3",
    ownerId: "u3",
    ownerName: "Lucia Fernandez",
    ownerEmail: "lucia.fernandez@school.edu",
    city: "Madrid",
    neighbourhood: "Malasaña",
    rent: 680,
    currency: "EUR",
    availableFrom: "2026-01-01",
    availableUntil: "2026-07-31",
    rooms: 1,
    description:
      "Charming studio in the heart of Malasaña, surrounded by bars, shops and vintage stores. Perfect for students.",
    photos: [],
    status: "active",
    createdAt: "2025-11-05T10:00:00.000Z",
  },
  {
    id: "4",
    ownerId: "u4",
    ownerName: "Diego Torres",
    ownerEmail: "diego.torres@school.edu",
    city: "Madrid",
    neighbourhood: "Chamberí",
    rent: 720,
    currency: "EUR",
    availableFrom: "2026-03-01",
    availableUntil: null,
    rooms: 1,
    description:
      "Quiet one-bedroom flat in the residential Chamberí area, 10 minutes walk from Complutense University.",
    photos: [],
    status: "active",
    createdAt: "2025-11-06T10:00:00.000Z",
  },
  {
    id: "5",
    ownerId: "u5",
    ownerName: "Nora Meier",
    ownerEmail: "nora.meier@school.edu",
    city: "Geneva",
    neighbourhood: "Plainpalais",
    rent: 1100,
    currency: "CHF",
    availableFrom: "2026-01-20",
    availableUntil: "2026-06-15",
    rooms: 1,
    description:
      "Sunny studio near Plainpalais market and the university. Includes a small balcony and shared laundry room.",
    photos: [],
    status: "active",
    createdAt: "2025-11-07T10:00:00.000Z",
  },
  {
    id: "6",
    ownerId: "u6",
    ownerName: "Julien Dubois",
    ownerEmail: "julien.dubois@school.edu",
    city: "Geneva",
    neighbourhood: "Eaux-Vives",
    rent: 1350,
    currency: "CHF",
    availableFrom: "2026-02-15",
    availableUntil: null,
    rooms: 2,
    description:
      "Spacious two-room apartment close to the lake in Eaux-Vives, 15 minutes by bus from campus.",
    photos: [],
    status: "active",
    createdAt: "2025-11-08T10:00:00.000Z",
  },
  {
    id: "7",
    ownerId: "u7",
    ownerName: "Camille Laurent",
    ownerEmail: "camille.laurent@school.edu",
    city: "Paris",
    neighbourhood: "Le Marais",
    rent: 950,
    currency: "EUR",
    availableFrom: "2026-01-10",
    availableUntil: "2026-08-31",
    rooms: 1,
    description:
      "Small but charming studio in Le Marais, close to metro lines 1 and 11. Ideal for a semester abroad.",
    photos: [],
    status: "active",
    createdAt: "2025-11-09T10:00:00.000Z",
  },
  {
    id: "8",
    ownerId: "u8",
    ownerName: "Hugo Martin",
    ownerEmail: "hugo.martin@school.edu",
    city: "Paris",
    neighbourhood: "Bastille",
    rent: 1050,
    currency: "EUR",
    availableFrom: "2026-02-01",
    availableUntil: null,
    rooms: 2,
    description:
      "Modern two-room apartment near Bastille, recently renovated, 20 minutes to most Parisian campuses.",
    photos: [],
    status: "active",
    createdAt: "2025-11-10T10:00:00.000Z",
  },
  {
    id: "9",
    ownerId: "u9",
    ownerName: "Emma Roux",
    ownerEmail: "emma.roux@school.edu",
    city: "Marseille",
    neighbourhood: "Le Panier",
    rent: 600,
    currency: "EUR",
    availableFrom: "2026-01-05",
    availableUntil: "2026-06-30",
    rooms: 1,
    description:
      "Colorful studio in the historic Le Panier district, a few steps from the Vieux-Port and great views.",
    photos: [],
    status: "active",
    createdAt: "2025-11-11T10:00:00.000Z",
  },
  {
    id: "10",
    ownerId: "u10",
    ownerName: "Thomas Girard",
    ownerEmail: "thomas.girard@school.edu",
    city: "Marseille",
    neighbourhood: "La Joliette",
    rent: 650,
    currency: "EUR",
    availableFrom: "2026-03-01",
    availableUntil: null,
    rooms: 1,
    description:
      "Modern studio near La Joliette docks, close to tram lines and 25 minutes from the main campus.",
    photos: [],
    status: "active",
    createdAt: "2025-11-12T10:00:00.000Z",
  },
];
