import type { Listing } from "./types";

export const listings: Listing[] = [
  {
    id: "1",
    ownerId: "u1",
    ownerName: "Chiara Rossi",
    ownerEmail: "chiara.rossi@school.edu",
    city: "Milan",
    neighbourhood: "Navigli",
    rent: 750,
    currency: "EUR",
    availableFrom: "2026-01-15",
    availableUntil: null,
    rooms: 1,
    description:
      "Cozy studio a 5-minute walk from the Navigli canals. Bright, quiet courtyard-facing room, fully furnished.",
    photos: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
    ],
    status: "active",
    createdAt: "2026-09-14T10:00:00.000Z",
  },
  {
    id: "2",
    ownerId: "u2",
    ownerName: "Marco Bianchi",
    ownerEmail: "marco.bianchi@school.edu",
    city: "Milan",
    neighbourhood: "Città Studi",
    rent: 620,
    currency: "EUR",
    availableFrom: "2026-02-01",
    availableUntil: "2026-07-31",
    rooms: 2,
    description:
      "Shared apartment near the university campus, 10 minutes by bike. Perfect for a semester exchange.",
    photos: [],
    status: "active",
    createdAt: "2026-08-20T09:30:00.000Z",
  },
  {
    id: "3",
    ownerId: "u3",
    ownerName: "Lucía Fernández",
    ownerEmail: "lucia.fernandez@school.edu",
    city: "Madrid",
    neighbourhood: "Malasaña",
    rent: 680,
    currency: "EUR",
    availableFrom: "2026-01-01",
    availableUntil: null,
    rooms: 1,
    description:
      "Bright studio in the heart of Malasaña, surrounded by cafes and nightlife. Renovated in 2024.",
    photos: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
    ],
    status: "active",
    createdAt: "2026-09-16T14:00:00.000Z",
  },
  {
    id: "4",
    ownerId: "u4",
    ownerName: "Pablo Ruiz",
    ownerEmail: "pablo.ruiz@school.edu",
    city: "Madrid",
    neighbourhood: "Chamberí",
    rent: 550,
    currency: "EUR",
    availableFrom: "2026-03-01",
    availableUntil: null,
    rooms: 3,
    description:
      "Room in a 3-bedroom flat, shared with two friendly students. Close to metro Iglesia.",
    photos: [],
    status: "taken",
    createdAt: "2026-07-05T12:00:00.000Z",
  },
  {
    id: "5",
    ownerId: "u5",
    ownerName: "Elena Dubois",
    ownerEmail: "elena.dubois@school.edu",
    city: "Geneva",
    neighbourhood: "Plainpalais",
    rent: 1100,
    currency: "CHF",
    availableFrom: "2026-01-20",
    availableUntil: null,
    rooms: 1,
    description:
      "Modern studio near Plaine de Plainpalais, close to the tram and the market square.",
    photos: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
    ],
    status: "active",
    createdAt: "2026-09-12T08:00:00.000Z",
  },
  {
    id: "6",
    ownerId: "u6",
    ownerName: "Julien Moreau",
    ownerEmail: "julien.moreau@school.edu",
    city: "Geneva",
    neighbourhood: "Eaux-Vives",
    rent: 950,
    currency: "CHF",
    availableFrom: "2026-02-15",
    availableUntil: "2026-06-30",
    rooms: 2,
    description:
      "Sunny room in a shared flat close to the lake, 15 minutes walk from campus.",
    photos: [],
    status: "active",
    createdAt: "2026-06-01T11:00:00.000Z",
  },
  {
    id: "7",
    ownerId: "u7",
    ownerName: "Camille Laurent",
    ownerEmail: "camille.laurent@school.edu",
    city: "Paris",
    neighbourhood: "Le Marais",
    rent: 900,
    currency: "EUR",
    availableFrom: "2026-01-10",
    availableUntil: null,
    rooms: 1,
    description:
      "Charming studio in Le Marais, top floor with a view of the rooftops. Well connected by metro.",
    photos: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
    ],
    status: "active",
    createdAt: "2026-09-15T16:20:00.000Z",
  },
  {
    id: "8",
    ownerId: "u8",
    ownerName: "Hugo Bernard",
    ownerEmail: "hugo.bernard@school.edu",
    city: "Paris",
    neighbourhood: "Belleville",
    rent: 720,
    currency: "EUR",
    availableFrom: "2026-04-01",
    availableUntil: null,
    rooms: 2,
    description:
      "Room in a colorful shared flat in Belleville, lively neighbourhood with great food markets.",
    photos: [],
    status: "active",
    createdAt: "2026-08-01T09:00:00.000Z",
  },
  {
    id: "9",
    ownerId: "u9",
    ownerName: "Manon Girard",
    ownerEmail: "manon.girard@school.edu",
    city: "Marseille",
    neighbourhood: "Le Panier",
    rent: 600,
    currency: "EUR",
    availableFrom: "2026-01-05",
    availableUntil: null,
    rooms: 1,
    description:
      "Studio in the picturesque Le Panier district, a few steps from the old port.",
    photos: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800",
    ],
    status: "active",
    createdAt: "2026-09-10T13:00:00.000Z",
  },
  {
    id: "10",
    ownerId: "u10",
    ownerName: "Thomas Petit",
    ownerEmail: "thomas.petit@school.edu",
    city: "Marseille",
    neighbourhood: "La Joliette",
    rent: 520,
    currency: "EUR",
    availableFrom: "2026-02-10",
    availableUntil: null,
    rooms: 1,
    description:
      "Modern studio close to the business district and the ferry terminal. Sea view from the balcony.",
    photos: [],
    status: "active",
    createdAt: "2026-05-15T10:00:00.000Z",
  },
];
